Parameters:
  KeyName:
    Description: SSH key pair to use for instance login
    Type: AWS::EC2::KeyPair::KeyName
  AcceptRStudioLicenseAndInstall:
    Description: This CFN template installs RStudio Server to an EC2 instance. Please review and accept the AGPL v3 license http://www.gnu.org/licenses/agpl-3.0-standalone.html. 
    Type: String
    Default: Deny
    AllowedValues:
      - Accept
      - Deny

Conditions:
  ShouldCreateInstance:
    !Equals [Accept, !Ref AcceptRStudioLicenseAndInstall]
  DenyInstallation:
    !Equals [Deny, !Ref AcceptRStudioLicenseAndInstall]
#mappings between regions and amis to launch    
Mappings:
  Region:
    us-east-1:
      HostAmi: ami-0ff8a91507f77f867
    us-east-2:
      HostAmi: ami-0b59bfac6be064b78
    us-west-2:
      HostAmi: ami-a0cfeed8
    eu-west-1:
      HostAmi: ami-047bb4163c506cd98

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Condition: ShouldCreateInstance
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: RStudio SageMaker VPC

  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: ShouldCreateInstance
    Properties:
      RouteTableIds:
        - !Ref PublicRouteTable
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: ShouldCreateInstance
    Properties:
      Tags:
      - Key: Name
        Value: RStudio SageMaker Internet Gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: ShouldCreateInstance
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Condition: ShouldCreateInstance
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: RStudio SageMaker Public Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Condition: ShouldCreateInstance
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RStudio SageMaker Public Route Table

  PublicRoute:
    Type: AWS::EC2::Route
    Condition: ShouldCreateInstance
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: ShouldCreateInstance
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  Instance:
    Type: AWS::EC2::Instance
    Condition: ShouldCreateInstance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: t3.xlarge 
      ImageId: !FindInMap [Region, !Ref "AWS::Region", HostAmi]
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - Ref: PublicSubnetSecurityGroup
      Tags:
        - Key: Name
          Value: RStudio Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum update -y > /dev/null
          sudo yum install -y R libcurl-devel openssl-devel libxml2-devel docker  > /dev/null
          sudo pip install sagemaker boto3  > /dev/null
          sudo R -e "install.packages(c('reticulate', 'readr', 'curl', 'ggplot2', 'dplyr', 'stringr'), repos = 'http://cran.rstudio.com')"  > /dev/null
          sudo adduser rstudio #Change this to change the user
          sudo sh -c "echo rstudio7862 | passwd rstudio --stdin" #change this to change the password  > /dev/null
          wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.3.1056-x86_64.rpm  > /dev/null
          sudo yum install -y rstudio-server-rhel-1.3.1056-x86_64.rpm  > /dev/null
          sudo -u rstudio mkdir /home/rstudio/.aws 
          region=`curl http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}'`
          sudo -u rstudio echo "[default]" > /home/rstudio/.aws/config
          sudo -u rstudio echo "region =" $region >> /home/rstudio/.aws/config
          sudo rstudio-server restart  > /dev/null
          sudo service docker start  > /dev/null
          sudo usermod -a -G docker ec2-user  > /dev/null
          sudo usermod -a -G docker rstudio  > /dev/null
          sudo -u rstudio R -e "library(reticulate);install_miniconda(); conda_install(envname = 'r-reticulate', packages=c('sagemaker-python-sdk==2.5.5', 'pandas'));"  > /dev/null
          

  PublicSubnetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: ShouldCreateInstance
    Properties:
      GroupName: rstudio-sagemaker-sg
      GroupDescription: RStudio SageMaker Instance Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: 0.0.0.0/0
          FromPort: '8787'
          IpProtocol: tcp
          ToPort: '8787'

  EC2Role:
    Type: AWS::IAM::Role
    Condition: ShouldCreateInstance
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      RoleName: ec2-rstudio-sagemaker

  SageMakerRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateInstance
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      RoleName: sagemaker-service-role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: ShouldCreateInstance
    Properties:
      Path: "/"
      Roles:
      - Ref: EC2Role
      InstanceProfileName: rstudio-sagemaker-instance

Outputs:
  RStudio:
    Condition: ShouldCreateInstance
    Description: RStudio SSH command
    Value: !Sub "ssh -L 8787:localhost:8787 -i ${KeyName}.pem ec2-user@${Instance.PublicDnsName}"
  
  RStudioURL:
    Condition: ShouldCreateInstance
    Description: RStudio public URL
    Value: !Sub "${Instance.PublicDnsName}:8787"

  RStudioAGPLv3Licence:
    Condition: DenyInstallation
    Description: This CFN template installs RStudio Server to an EC2 instance. Please restart the stack creation process, review and accept the AGPL v3 license http://www.gnu.org/licenses/agpl-3.0-standalone.html.
    Value: "Denied"